tmux_dir="~/.config/tmux"
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

# Undercurl

set-option -g default-terminal "screen-256color"
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'                                                          # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' # underscore colours - needs tmux-3.0

# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Reload configuration
bind r source-file ~/.config/tmux/tmux.conf \; display '~/.config/tmux/tmux.conf sourced'


# 0 is too far from `
set -g base-index 1

# Tab bar
set-option -g status-position top


# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
# Enable copy-pasting
set -g set-clipboard on

# split horizontally
bind v split-window -v

# split vertical
bind h split-window -h


# Colorscheme
# source-file ~/.config/tmux/colors/teide-dark.tmux.conf
color_bg="#171B20"
color_fg="#E7EAEE"
color_text="#171B20"
color_comment="#586172"
color_date="#5CCEFF"
color_time="#FFDB70"
color_alert="#F97791"
color_pomodoro="#F5335A"
color_session="#38FFA5"
color_window="#545c7e"


# set status-interval 1

set -g status-bg $color_bg
set -g status-fg $color_fg
set -g status-justify left

set -g status-left-length 100
set -g status-left-style bg=$color_session,fg=$color_text,none
set -g status-left " #S "

set -g status-right-style bg=$color_date,fg=$color_text,none
set -g status-right-length 102
set -g status-right " #{?#{pane_ssh_connected},#U @ #H#[default],local} "

set -g window-status-separator "│" # |, │, ┃, , 
set -g window-status-format "  #W  "
set -g window-status-current-format "  #W  "


set -g window-status-current-style fg=$color_fg,bg=$color_bg,bold
set -g window-status-style fg=$color_comment,bg=$color_bg,none
# set -g window-status-activity-style italic

# Plugin manager
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b "${TMUX_PLUGIN_MANAGER_PATH}tpm/tpm"
