local M = {}

M.kind = {
  -- Method = '󰊕',
  -- Function = '󰊕',
  -- Constructor = '󰒓',

  Field = '󰜢',
  -- Variable = '󰆦',
  -- Property = '󰖷',

  -- Class = '󱡠',
  -- Interface = '󱡠',
  -- Struct = '󱡠',
  -- Module = '󰅩',

  -- Unit = '󰪚',
  -- Value = '󰦨',
  -- Enum = '󰦨',
  -- EnumMember = '󰦨',

  -- Keyword = '󰻾',
  -- Constant = '󰏿',

  -- Snippet = '󱄽',
  -- Color = '󰏘',
  -- File = '󰈔',
  -- Reference = '󰬲',
  -- Folder = '󰉋',
  -- Event = '󱐋',
  -- Operator = '󰪚',
  -- TypeParameter = '󰬛',
  Namespace = "󰌗",

  Method = "󰆧",
  Function = "󰆧",
  Constructor = "",
  -- Field = "󰜢",
  -- Variable = "󰀫",
  -- Class = "󰠱",
  -- Interface = "",
  -- Module = "",
  -- Property = "󰜢",
  -- Unit = "󰑭",
  -- Value = "󰎠",
  -- Enum = "",
  -- Keyword = "󰌋",
  -- Snippet = "",
  Color = "󱓻",
  -- File = "󰈚",
  -- Reference = "󰈇",
  Folder = "󰉋",
  -- EnumMember = "",
  -- Constant = "󰏿",
  -- Struct = "󰙅",
  -- Event = "",
  -- Operator = "󰆕",
  -- TypeParameter = "󰊄",
  Table = "",
  Object = "󰅩",
  Tag = "",
  Array = "[]",
  Boolean = "",
  Number = "",
  Null = "󰟢",
  Supermaven = "",
  String = "󰉿",
  Calendar = "",
  Watch = "󰥔",
  Package = "",
  Copilot = "",
  Codeium = "",
  TabNine = "",
  BladeNav = "",

  Text = '',
  -- Method = '  ',
  -- Function = '  ',
  -- Constructor = '  ',
  -- Field = '  ',
  Variable = '',
  Class = '',
  Interface = '',
  Module = ' ',
  Property = '',
  Unit = '',
  Value = '',
  Enum = '',
  Keyword = '',
  Snippet = '',
  -- Color = '  ',
  File = '',
  Reference = '',
  -- Folder = '  ',
  EnumMember = '',
  Constant = '',
  Struct = '',
  Event = '',
  Operator = '',
  TypeParameter = '',
}

return M
