local M = {}
-- icons
M.dashboard = {
	lazy = "󰒲 ",
	update = " ",
	sync = " ",
	mason = "  ",
	telescope = "  ",
	exit = " ",
}
M.lualine = {
	left_bar = "▊",
	right_bar = "▊",
	right_curve = "",
	left_curve = "",
	right_triangle = " ",
	left_triangle = "",
	status_left = " ",
	branch = "",
	add = " ",
	change = " ",
	delete = " ",
	lsp_icon = " ",
	error = " ",
	warn = " ",
	hint = " ",
	info = " ",
	select = " ",
	terminal = " ",
	replace = " ",
	status_right_pop = " ",
	status_right_mac = " ",
}
M.neotree = {
	default = " ",
	symlink = " ",
	bookmark = " ",
	folder = {
		arrow_closed = " ",
		arrow_open = " ",
		default = " ",
		open = " ",
		empty = " ",
		closed = " ",
		empty_open = " ",
		symlink = " ",
		symlink_open = " ",
		symlink_arrow = "  ",
	},
	file = {
		modified = "󱇨 ",
	},
	git = {
		unstaged = " ",
		staged = " ",
		unmerged = " ",
		renamed = " ",
		untracked = " ",
		deleted = " ",
		ignored = " ",
		conflict = "裂",
	},
}
M.diff = {
	added = "",
	modified = "",
	removed = "",
	ignore = "",
}
M.diagnostic = {
	error = "",
	warn = "",
	hint = "",
	info = "",
	question = "",
}

M.cmp_kinds = {
	Text = "",
	Unit = "",
	Value = "",
	Keyword = "",
	Snippet = "",
	Color = "",
	Reference = "",
	-- Folder = "",
	Folder = "󰉋",
	Operator = "",
	TypeParameter = "",
	File = "",
	Module = "",
	Namespace = "",
	Package = "",
	Class = "",
	Method = "",
	Property = "",
	Field = "",
	Constructor = "",
	Enum = "",
	Interface = "",
	Function = "",
	Variable = "",
	Constant = "",
	String = "",
	Number = "",
	Boolean = "",
	Array = "",
	Object = "",
	Key = "",
	Null = "",
	EnumMember = "",
	Struct = "",
	Event = "",
}

M.ui = {
	ArrowClosed = "",
	ArrowOpen = "",
	Lock = " ",
	Circle = "󰧞",
	BigCircle = " ",
	BigUnfilledCircle = " ",
	Close = "",
	NewFile = " ",
	Search = " ",
	Lightbulb = " ",
	Project = " ",
	Dashboard = " ",
	History = " ",
	Comment = " ",
	Bug = " ",
	Code = " ",
	Telescope = " ",
	Gear = " ",
	Package = " ",
	List = " ",
	SignIn = " ",
	SignOut = " ",
	NoteBook = " ",
	Check = " ",
	Fire = " ",
	Note = " ",
	BookMark = " ",
	Pencil = " ",
	ChevronRight = "",
	Table = " ",
	Calendar = " ",
	CloudDownload = " ",
	lineVertical = "│",
	Help = "󰋖",
	Folder = "󰉋",
	FolderOpen = "",
	EmptyOpen = "",
	Empty = "",
	Term = "",
	Atom = "󰹻",
	borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
}
M.devicons = {
	default_icon = {
		icon = "󰈚",
	},

	c = {
		icon = "",
		color = "#0288d1",
	},

	css = {
		icon = "",
		color = "#42a5f5",
	},
	html = {
		icon = "󰌝",
		color = "#e44d26",
	},

	lua = {
		icon = "󰢱",
		color = "#42a5f5",
	},
	py = {
		icon = "",
		color = "#3c78aa",
	},
	tex = {
		icon = "",
		color = "#42a5f5",
	},
}
return M
