local M = {}
-- icons
M.icons = {
    dashboard = {
        lazy = "󰒲 ",
        update = " ",
        sync = " ",
        mason = "  ",
        telescope = "  ",
        exit = " ",
    },
    lualine = {
        left_bar = "▊",
        right_bar = "▊",
        status_left = "",
        branch = "",
        add = " ",
        change = " ",
        delete = " ",
        lsp_icon = "",
        error = " ",
        warn = " ",
        hint = " ",
        info = " ",
        select = " ",
        terminal = " ",
        replace = " ",
        status_right_pop = " ",
        status_right_mac = " ",
    },
    neotree = {
        default = " ",
        symlink = " ",
        bookmark = " ",
        folder = {
            arrow_closed = " ",
            arrow_open = " ",
            default = " ",
            open = " ",
            empty = " ",
            closed = " ",
            empty_open = " ",
            symlink = " ",
            symlink_open = " ",
            symlink_arrow = "  ",
        },
        file = {
            modified = "󱇨 ",
        },
        git = {
            unstaged = " ",
            staged = " ",
            unmerged = " ",
            renamed = " ",
            untracked = " ",
            deleted = " ",
            ignored = " ",
            conflict = "裂",
        },
    },
}

M.diagnostic = {
    error = "",
    warn = "",
    hint = "",
    info = "",
    question = "",
}

M.cmp_kinds = {
    Text = "",
    Unit = "",
    Value = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    Reference = "",
    Folder = "",
    Operator = "",
    TypeParameter = "",
    File = "",
    Module = "",
    Namespace = "",
    Package = "",
    Class = "",
    Method = "",
    Property = "",
    Field = "",
    Constructor = "",
    Enum = "",
    Interface = "",
    Function = "",
    Variable = "",
    Constant = "",
    String = "",
    Number = "",
    Boolean = "",
    Array = "",
    Object = "",
    Key = "",
    Null = "",
    EnumMember = "",
    Struct = "",
    Event = "",
}

M.ui = {
    ArrowClosed = "",
    ArrowOpen = "",
    Lock = " ",
    Circle = "",
    BigCircle = " ",
    BigUnfilledCircle = " ",
    Close = "",
    NewFile = " ",
    Search = " ",
    Lightbulb = " ",
    Project = " ",
    Dashboard = " ",
    History = " ",
    Comment = " ",
    Bug = " ",
    Code = " ",
    Telescope = " ",
    Gear = " ",
    Package = " ",
    List = " ",
    SignIn = " ",
    SignOut = " ",
    NoteBook = " ",
    Check = " ",
    Fire = " ",
    Note = " ",
    BookMark = " ",
    Pencil = " ",
    ChevronRight = "",
    Table = " ",
    Calendar = " ",
    CloudDownload = " ",
    lineVertical = "│",
    Help = "󰋖",
    Folder = "󰉋",
    FolderOpen = "",
    EmptyOpen = "",
    Empty = "",
    Term = "",
    Atom = "󰹻",
    borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
}

return M
