scan_timeout = 60
add_newline = false

[line_break]
disabled = false

[directory]
style = "bold blue"


[character]
success_symbol = '[](bold green)'


[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = ""
map_symbol = true
symbol = ''
success_symbol = ''


[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "
