
local M = {}
M.icons = {
  misc = {
    dots = "󰇘",
  },
  dap = {
    Stopped             = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint          = " ",
    BreakpointCondition = " ",
    BreakpointRejected  = { " ", "DiagnosticError" },
    LogPoint            = ".>",
  },
  diagnostics = {
    -- Error = " ",
    -- Warn  = " ",
    Hint = " ",
    -- Info  = " ",
    Error = "󰅚 ",
    Warn = "󰀪 ",
    -- Hint = "󰌶 ",
    Info = " "
  },
  git = {
    added    = " ",
    modified = " ",
    removed  = " ",
  },
  kinds = {
    Array         = " ",
    Boolean       = "󰨙 ",
    Class         = " ",
    Codeium       = "󰘦 ",
    Color         = " ",
    Control       = " ",
    Collapsed     = " ",
    Constructor   = " ",
    Copilot       = " ",
    Enum          = " ",
    Event         = " ",
    File          = " ",
    Keyword       = " ",
    Function      = "󰊕 ",
    Module        = " ",
    TabNine       = "󰏚 ",
    Text          = " ",
    Unit          = " ",
    Value         = " ",
    Snippet       = " ",
    Reference     = " ",
    -- Folder = "",
    Folder        = "󰉋 ",
    Operator      = " ",
    TypeParameter = " ",
    Namespace     = " ",
    Package       = " ",
    Method        = " ",
    Property      = " ",
    Field         = " ",
    Interface     = " ",
    Variable      = " ",
    Constant      = " ",
    String        = " ",
    Number        = " ",
    Object        = " ",
    Key           = " ",
    Null          = " ",
    EnumMember    = " ",
    Struct        = " ",
  },

  ui = {
    ArrowClosed = "",
    ArrowOpen = "",
    Lock = " ",
    Circle = "󰧞",
    BigCircle = " ",
    BigUnfilledCircle = " ",
    Close = "",
    NewFile = " ",
    Search = " ",
    Lightbulb = " ",
    Project = " ",
    Dashboard = " ",
    History = " ",
    Comment = " ",
    Bug = " ",
    Code = " ",
    Telescope = " ",
    Gear = " ",
    Package = " ",
    List = " ",
    SignIn = " ",
    SignOut = " ",
    NoteBook = " ",
    Check = " ",
    Fire = " ",
    Note = " ",
    BookMark = " ",
    Pencil = " ",
    ChevronRight = "",
    Table = " ",
    Calendar = " ",
    CloudDownload = " ",
    lineVertical = "│",
    lineVerticalLeft = "▏",
    Help = "󰋖",
    Folder = "󰉋",
    FolderOpen = "",
    EmptyOpen = "",
    Empty = "",
    Term = "",
    Atom = "󰹻",
    borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },

    devicons = {
      default_icon = {
        icon = "󰈚",
      },

      c = {
        icon = "",
        color = "#0288d1",
      },

      css = {
        icon = "",
        color = "#42a5f5",
      },
      html = {
        icon = "󰌝",
        color = "#e44d26",
      },

      lua = {
        icon = "󰢱",
        color = "#42a5f5",
      },
      py = {
        icon = "",
        color = "#3c78aa",
      },
      tex = {
        icon = "",
        color = "#42a5f5",
      },
    }
  }
}

return M
