
# Alacritty Configuration for WSL2 + Arch Linux
[window]
dimensions = { columns = 120, lines = 20 }
padding = { x = 6, y = 1 }
# decorations = "None"
dynamic_padding = true

# opacity = 0.95
blur = true
[font]
normal = { family = "ComicShannsMono Nerd Font Propo" }
# bold = { family = "ComicShannsMono Nerd Font", style = "Bold" }
# italic = { family = "ComicShannsMono Nerd Font", style = "Italic" }
size = 12.0
offset = { x = 0, y = 8 }
glyph_offset = { x = 0, y = 2 }
builtin_box_drawing = true #true | false


[terminal]
# shell = { program = "wsl", args = [ "~"] }
# args = ["~"]
osc52="CopyPaste"

[mouse]
hide_when_typing = true


[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#0A0A0A"
foreground = "#CDD6F4"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"

background = "#585B70"

[colors.normal]
black   = "#45475A"

red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"

blue    = "#89B4FA"
magenta = "#F5C2E7"
cyan    = "#94E2D5"
white   = "#BAC2DE"


[colors.bright]
black   = "#585B70"
red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"
blue    = "#89B4FA"
magenta = "#F5C2E7"
cyan    = "#94E2D5"
white   = "#A6ADC8"

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F11",      action = "ToggleFullscreen" }
]

