# custom_cursor_colors = true
# hide_cursor_when_typing = true
import = ["/home/percy/.config/alacritty/material.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "CasKaydiaCove Nerd Font"
style = "Regular"

[shell]
program = "/bin/fish"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 1

[window.dimensions]
columns = 130
lines = 32

