[colors.bright]
black = "#545454"
blue = "#82AAFF"
cyan = "#89DDFF"
green = "#C3E88D"
magenta = "#C792EA"
red = "#FF5370"
white = "#FFFFFF"
yellow = "#FFCB6B"

[colors.normal]
black = "#000000"
blue = "#82AAFF"
cyan = "#89DDFF"
green = "#C3E88D"
magenta = "#C792EA"
red = "#FF5370"
white = "#FFFFFF"
yellow = "#FFCB6B"

[colors.primary]
background = "#212121"
foreground = "#EEFFFF"
