require("plugins.configs.winbar")

require("plugins.configs.nvimtree")
require("plugins.configs.cmp")
require("plugins.configs.lsp")
require("plugins.configs.lualine")
require("plugins.configs.bufferline")
require("plugins.configs.treesitter")
require("plugins.configs.ts-context")
require("plugins.configs.comment")
require("plugins.configs.alpha")
require("plugins.configs.indent-blankline")
require("plugins.configs.gitsigns")
require("plugins.configs.cursorline")

-- require("plugins.configs.whick-key")
require("plugins.configs.telescope")
