require('core.keymaps')
require('core.ui')
require('core.options')


require('plugins')
require('plugins.plugConfig.nvimtree')
--require('plugins.plugConfig.coc')
require('plugins.plugConfig.lualine')
require('plugins.plugConfig.treesitter')
require('plugins.plugConfig.indentline')
require('plugins.plugConfig.gitsigns')
require('plugins.plugConfig.bufferline')
require('plugins.plugConfig.telescope')
require('plugins.plugConfig.whichKey')
require('plugins.plugConfig.colorizer')
require('plugins.plugConfig.ts-context')
require('plugins.plugConfig.alpha')
require('plugins.plugConfig.illuminate')
require('plugins.plugConfig.cmp')
require('plugins.plugConfig.lsp')
